image: archlinux
packages:
  - make
  - mkrom
  - patchrom
  - genkfs
  - mktiupgrade
  - valgrind
sources:
  - https://git.sr.ht/~pixelherodev/scas
  - https://github.com/knightos/kernel
tasks:
  - build: |
      cd scas
      make bin/scas
      cd ../../kernel
      # Temporary: use scas PR
      git checkout scas
      mkdir bin/TI84pSE -p
      make AS="valgrind --track-origins=yes --leak-check=full --error-exitcode=1 ../scas/bin/scas"

